### ISSUE TITLE
Angular 9 build fails due to NgPerfume error

### ISSUE THREAD

**Issue by adover** [Zizzamia/perfume.js#110]
Hi all,
When trying to run an `ng build` with NgPerfume added I am getting this error:

```
ERROR in node_modules/perfume.js/angular/lib/perfume.module.d.ts:19:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

19     static ɵfac: i0.ɵɵFactoryDef<NgPerfume>;
```

Using Angular 9.1.0 and Perfume 4.7.0

EDIT: This can be fixed by adding `"skipLibCheck": true` to the tsconfig.json, although this is not ideal

**Comment by Zizzamia** [comment]
@adover if you know how to solve it, would you mind make a PR for it?

**Comment by Zizzamia** [comment]
@mgechev do you know this issue what is about?

**Comment by Zizzamia** [comment]
@adover actually I decided to stop supporting custom Framework version starting from v5 https://github.com/Zizzamia/perfume.js/releases/tag/v5.0.0-rc.1  ☕️, mostly because Perfume is a very simple Vanilla library which is not too hard to include in any library. Sorry if this news it comes out without a proper warning.

Perfume.js v5 contains some breaking changes so please feel free to open a new issue or ask me more questions if something unusual comes up.

Grazie Mille 💛
