### ISSUE TITLE
Determine JS Parse Time vs Network load time

### ISSUE THREAD

**Issue by dan-kez** [Zizzamia/perfume.js#123]
Hello!

Is there a way using this library to be able to measure the JS parse time for a downloaded js file? 

Basically I'm looking to measure the download time (network dependent) vs js parse time (cpu dependent).

Thanks for making this lib!

**Comment by Zizzamia** [comment]
Ciao! Very interesting question, why are you trying to measure JS Parse Time in particular?
Are you measuring inside a Single Page App, or Server Side Rendered?

If you are in a Single Page App you can measure
- **network time**: use Time To First Byte, which is contained inside the [Navigation Timing](https://github.com/Zizzamia/perfume.js#navigation-timing).
- **parse time**: is generally contained inside First Contentful Paint because you need Parse your Javascript to then generate the First Contentful Paint. Here just an example that shows the initial time parse HTML/JS before Painting for this page.

<img width="1348" alt="Screen Shot 2020-05-27 at 10 02 55 PM" src="https://user-images.githubusercontent.com/829214/83100980-0e955f00-a066-11ea-9204-c1d65970e222.png">

But @dan-kez if you are looking for the most direct resource to do that, you need to play a little in a custom metric world.

Something like
```html
<script>
  window.perfume = new Perfume({
    analyticsTracker: ({ metricName, data }) => {
      myAnalyticsTool.track(metricName, data);
    })
  });
  perfume.start('jsParse');
</script>
<script src="app.js"></script>
<script>
  perfume.end('jsParse');
</script>
```
I personally would avoid to measure Parse JS in the field, and instead focus more on FCP, LCP and TBT. They are easier to measure and bullet-proof on the quality of data you can achieve with them.

**Comment by dan-kez** [comment]
Thanks for the detailed and thoughtful answer!

The product I work on is actually client side rendered embedded content. For example, an ecommerce store would add my JS snippet and I will affect their site either adding or changing content that is displayed.

Many of these changes are expected to happen as close to page load as possible while not being a blocking script. From some basic testing, JS parse time was taking a non trivial amount of time on a throttled cpu and blocking the main thread until I made some optimizations.

When I use the performance tool in chrome I can get a decent sense of where the time is going and how long I am blocking the main thread to catch any regressions. That said, I'd like for this to be something I can monitor automatically and see if things are regressing over time. 

I could attempt to write an automated environment to do run this in CI but it would be nice to monitor it in production.

Many metrics like FCP, LCP, and TBT are not really applicable since we do not own the majority of the DOM and many of our customers .. do not have the most efficient sites. 

If you have any recommendations on other aspects to measure given that I don't own the site which my code is running I would really appreciate it!

**Comment by Zizzamia** [comment]
If I was building an embedded content I will not focus much my attention on Field Data, but more on Lab Data. So I don't think Perfume.js is the best option for this case, but instead, I will focus more on the adoption of Puppeteer, and in particular, I will read carefully the [Web Performance Recipes With Puppeteer](https://addyosmani.com/blog/puppeteer-recipes/) article.

I will probably build a simple HTML page with your code as the only JS code and measure the time it takes to parse.

**Comment by Zizzamia** [comment]
Closing this thread as it looks stale.
