### ISSUE TITLE
Many of the metric events are not getting recorded

### ISSUE THREAD

**Issue by nitinagrawal08** [Zizzamia/perfume.js#145]
We are using perfume.js for live tracking of users data for housing.com. What we have seen over the period of time that CLS metric is only getting recorded for 3% users and tbt for 30% users. Any clue why it would be happening like this? Configuration used
```
{
resourceTiming: true,
maxMeasureTime: 15000,
}
```
Environment - React

**Comment by Zizzamia** [comment]
Ciao @nitinagrawal08,
would you mind share more about:
- what version of Perfume.js are you running
- what's the percentage of your users on Chrome
- can you share the percentage of all the other as well, like % of `fcp`, `lcp`, `fid` and so on
- are you running as SPA or SSR

Just for context, the reason I asked about Chrome is because the library depends on the [PerformanceObserver API](https://caniuse.com/?search=performanceObserver).

Thank you for opening this question, looking forward to understand better what's going on.

**Comment by paulincai** [comment]
@nitinagrawal08 somebody invested 5 minutes and replied to your query. As a minimum you could just say "thank you."

**Comment by Zizzamia** [comment]
Closing this issue after a few months of lack of reply.
