### ISSUE TITLE
FPS feature.

### ISSUE THREAD

**Issue by DanielSokil** [Zizzamia/perfume.js#21]
Ability to get Average `FPS` performance from `First Contentful Paint` to `Time to Interactive`

Start `First Contentful Paint`
![screenshot from 2018-02-14 17-56-23](https://user-images.githubusercontent.com/24403355/36232762-05bcef88-11b1-11e8-89f4-78d48b33e57e.png)

End `Time to Interactive`
![screenshot from 2018-02-14 17-57-21](https://user-images.githubusercontent.com/24403355/36232774-10766422-11b1-11e8-90e5-fb8c7e86134c.png)

Average `FPS` from `First Contentful Paint` till `Time to Interactive`
![screenshot from 2018-02-14 17-57-57](https://user-images.githubusercontent.com/24403355/36232807-38570bcc-11b1-11e8-8914-2c8d51805cb2.png)

**Comment by Zizzamia** [comment]
Can you link me to some documentation or Web API related?

**Comment by DanielSokil** [comment]
@Zizzamia https://github.com/victornpb/micro-fps/blob/master/src/index.js

**Comment by Zizzamia** [comment]
I spent some time researching about FPS, and the most close official proposal is [LatencyInfo Based Frame Metric](https://docs.google.com/document/d/1KrqWnzGNm7qUqSLer-iXiGxVC-nL7niZtEU-0rU0W08/edit).

Because it seems like there is not a strong support from the Chrome team to support this metric, I prefer not to add it to Perfume, yet.

@paulirish am I missing any recent update about it?
