### ISSUE TITLE
Remove Time To Interactive from Perfume

### ISSUE THREAD

**Issue by Zizzamia** [Zizzamia/perfume.js#54]
Based on https://developers.google.com/web/updates/2018/05/first-input-delay, it is advised to calculate TTI during Lab Measurements and use FID for RUM.

> TTI is a metric that can be measured without any users present, which means it's ideal for lab environments like Lighthouse or WebPageTest. Unfortunately, lab metrics, by their very nature, cannot measure real user pain.
> 
> FID, on the other hand, directly represents user pain—every single FID measurement is an instance of a user having to wait for the browser to respond to an event. And when that wait time is long, users will get frustrated and often leave.
> 
> For these reasons we recommend both metrics, but we recommend you measure TTI in lab and you measure FID in the wild, with your analytics tool.

**Comment by DmitryEfimenko** [comment]
Could you please explain the decision to remove the ability to measure TTI?
I was very sad to see it being removed as I think it's a very useful metric.
I understand there are lab tools like LightHouse that help us measure this, but it's also nice to be able to gather it in the wild. In this case, it's easy to set up an alarm if TTI goes crazy and have it investigated.

**Comment by Zizzamia** [comment]
I completely understand I felt like you when I discovered the TTI (like Pluto for the solar system) was kicked out from the RUM metrics. Perfume goal is to support the metrics are recognized to be the best and well supported by the W3C for your field user experience.
Three reasons:
1) Here it's explained how FID is a better metric for RUM instead of TTI: https://developers.google.com/web/updates/2018/05/first-input-delay
2) To measure the TTI we use [tti-polyfill](https://github.com/GoogleChromeLabs/tti-polyfill) build by @philipwalton, and the code as good as can be doesn't seem is going to be improved over time because of **point 1**.
3) Because the **tti-polyfill** does a lot of calculations to generate the **TTI** for you, this adds a level of stress to your initial load it doesn't seem worth the gain.

I'm working to release soon an open source [Lighthouse CLI](https://github.com/GoogleChrome/lighthouse) script to calculate everything you need for your web App and build a dashboard with it.

**Comment by DmitryEfimenko** [comment]
Thank you a lot for the explanation. It does make a lot of sense now.
Looking forward to your future work!

**Comment by nilskuhn** [comment]
I am still interested in measuring TTI in RUM for these reasons: 

1. I want to build my own KPI's aggregating multiple RUM metrics (like performance score of lighthouse does). While FID may be a better interactivity metric in RUM than TTI its values must be somehow normalized to be aggregated with other metrics (because they are typically much smaller  at least for median or average). Also I think TTI still has its meaning, despite his weaknesses in the RUM. 
2. I like the possibility to compare TTI values from RUM with these from our synthetic measurement setup (WPT based). 

@Zizzamia Did you ever measure the stress TTI polyfill adds to the load time of the integrating page (your reason 3 from above)?
I totally agree: Nobody wants to decrease performance by measuring it ;)

**Comment by Zizzamia** [comment]
@nilskuhn thank you for your feedback.
About point 3, I didn't personally double-check it. But I read the polyfill code quite extensively and there is a lot of calculations and network stress done by collecting all the resources need it for that metric.

If you are still interested to do some testing, feel free to take the [tti-polyfill ](https://github.com/GoogleChromeLabs/tti-polyfill) and play with it. 😄
