### ISSUE TITLE
Computing Paint Entries as per Spec Level 1

### ISSUE THREAD

**Issue by aroramayur** [Zizzamia/perfume.js#59]
Thank you for writing this @Zizzamia. I am looking at leveraging this to get paint performance information for my app. From all the documentation I've read , one should register PerformanceObserver in the `<head> `before any CSS loads to capture FP and FCP.

> Important: you must ensure your PerformanceObserver is registered in the `<head>` of your document before any stylesheets, so it runs before FP/FCP happens.

This is needed until Level 2 of the spec comes up with the 'buffered' flag - which is in editor's draft right now. How is Perfume capturing paint entries without registering the observer in `<head>` ?

**Comment by Zizzamia** [comment]
Thank you for pointing this out, I had a similar question over a year ago when I start building Perfume.js
What I learned is that dependence 😆as everything with measuring performance.

Over time **PerformanceObserver** will become better to be used everywhere in the application, for now, make sure to run **Perfume** as soon as possible in your stack, I personally do inside a Single Page App as one of the first object instantiated.

In the end, it's important to see the relative performance result over time getting better instead of focusing on absolute values. Also not forget that already for Field Data we have many false positive/negative, and it's important to look the bigger picture instead of the small details.

Use your user-centric metric to improve UX experience over all devices, and don't worry too much if the metric is 5~8% not accurate.
