### ISSUE TITLE
Inaccurate Paint Timing polyfill

### ISSUE THREAD

**Issue by csabapalfi** [Zizzamia/perfume.js#64]
I can see this library tries to polyfill the Paint Timing API but not sure if the implementation is accurate.

Here's the code I'm referring to: https://github.com/Zizzamia/perfume.js/blob/master/src/emulated-performance.ts#L33-L37

Would it be better to simply not return FP and FCP if the browser doesn't support Paint Timing? Maybe I'm missing something but how can a simple `setTimeout` capture anything related to paint timing?

**Comment by Zizzamia** [comment]
You make a great point! I'm going to think more about it and see if I should have a boolean option to enable/disable Paint Timing polyfill.

**Comment by csabapalfi** [comment]
Brilliant, thanks! 👍

**Comment by Zizzamia** [comment]
Ciao, and sorry for this late reply.
With V3 we will drop the support for Paint Timing polyfill and only serve the results from the Vanilla API 🍾
Also, we have the buffered flag enabled which will help for Server Side Rendering and Google Tag Manager issues. 🤩

You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)

I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.

**Comment by ElvisWang27** [comment]
> Ciao, and sorry for this late reply.
> With V3 we will drop the support for Paint Timing polyfill and only serve the results from the Vanilla API 🍾
> Also, we have the buffered flag enabled which will help for Server Side Rendering and Google Tag Manager issues. 🤩
> 
> You can already test it with [Perfume.js v3.0.0-rc.5](https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md)
> 
> I am going to have v3 under monitoring before release it officially, in case of possible cross browser bugs.

hello @Zizzamia , I want to know why drop the support for Paint Timing polyfill. As far as I know, the `PerformancePaintTming` isn't support in Safari and IOS,  is  meant  I cannot get the FCP or FP data in these browser or device without the polyfill?

**Comment by Zizzamia** [comment]
Ciao @ElvisWang27, long story short is a matter of accuracy of data. It's better have less data but accurate, that have more data but with extra noise that is hard to debug or have clear OKR to follow. About Safari, I think we are getting really close on supporting more and more performance metrics in the fields. Just recently @noamr added First Paint in the next Safari version (https://techblog.wikimedia.org/2020/06/24/how-we-contributed-paint-timing-api-to-webkit/).

In general with Web Vitals becoming the leading performance metrics and the Performance Observer slowly but shortly being the official standard for field data metrics, it is important to focus only on the best Vanilla support. Or at least this is what I notice in practice works better.

I use Perfume.js with all my personal and work production projects, and every update I do or breaking changes we introduce is because that particular feature or pattern didn't really pay dividends in practice. In the next version (v6) for example I will do a clean up on the Total Blocking Time options, this is because after 8 months of production data analysis, I learnt which one is the best option for SPA or SSR applications and how to better drive consistent goals and OKR with a large team.

I hope this brief explanation helps understand my point of view. Happy to chat more if you are looking what's the best strategy to set up in your company to drive a web performance culture driven by clear business metrics impact. Have a great week! 😄

**Comment by noamr** [comment]
Hi, I contributed to the paint timing spec and the Safari implementation.
I believe that it is impossible to accurately polyfill paint timing. One of two things would happen if you try:

- A very coarse implementation, which would give different results from vanilla in various edge cases, but would measure some of the key use cases.
- An implementation with significant overhead of its own, which would affect the results. Considering all the edge cases of paint timing would require calling `getComputedStyle` and `getBoundingClientRect` on elements, which is a costly operation and would end up affecting the results.

**Comment by ElvisWang27** [comment]
@Zizzamia Thanks for your time, In my project，the statistics about browser distribution show there are 10% customers use chrome version lower than 60, and 20% customer use IOS. So, when I did an optimization about FCP for my project, I want to know it's useful for these 30% customers.

I agree with your opinion about the mater of accuracy of data. And I have an idea to use the polyfill method without noise whole accuracy data,  can try to  make a distinguish forms  in the performance monitor system between these inaccuracy and accuracy data?

But according to @noamr said,It's impossible to accurately polyfill. I want to know how to make an implementation are  as accurate as possible without significant overhead of its own using these api such as `MutationObserver` , `getComputedStyle`, `getBoundingClientRect`, `requestAnimateFrame`, or DOM event and so on. And how much gap between the polyfill and real paint timing? 

Finally, thank you two great programmers for reading my poor English expression.

**Comment by noamr** [comment]
> l I want to know how to make an implementation are as accurate as possible without significant overhead of its own using these api such as `MutationObserver` , `getComputedStyle`, `getBoundingClientRect`, `requestAnimateFrame`, or DOM event and so on. And how much gap between the polyfill and real paint timing?

It depends on how much inaccuracies you are willing to live with and how much overhead, and for which content.

You can work with mutation observers and wait for text and image loads, and then approximate the visibility of those contentful elements with getComputedStyle etc, but the more elements you have, the more potential overhead.

I would say that it’s possible to build a decent polyfill that would for a particular page or set of pages and maybe even one that would work for a large number of existing pages on the internet, but would give a poor results for others.

I would suggest creating several other measurements that are quasi-paint timing, and call them in different names rather than have them pretending to be equivalent to first contentful paint
It

**Comment by vigneshshanmugam** [comment]
Adding to the above points, I tried doing the [polyfill](https://github.com/vigneshshanmugam/first-contentful-pain) for FCP which happens to be working for some of the cases, but its very hard to accurately claim the metric being very close to the actual metric exposed by the browsers. Also explained some of the [gotchas](https://github.com/vigneshshanmugam/first-contentful-paint#gotchas) in the library itself. Its hard to account for all of the [cases](https://w3c.github.io/paint-timing/#sec-terminology) without making the application slow as we have to observe for lots of elements on the page that could effectively paint something. 

> I would suggest creating several other measurements that are quasi-paint timing, and call them in different names rather than have them pretending to be equivalent to first contentful paint.

💯 agree with this point, personally preferred this pattern more than FCP as it provided better value proposition than having to rely on the FCP metric which doesn't always reflect the true user experience. This is based on the production data from some of the e-commerce companies i worked in the past.

**Comment by Zizzamia** [comment]
@ElvisWang27 working with Chrome before v60 has a few step back in terms of latest field data metrics. @noamr made a great point on trying to create a custom metric that focus on your pages and user experience. The best Performance API with the largest support for that is `performance.mark` ([browser support](https://caniuse.com/#feat=mdn-api_performancemark)), and with Perfume you can use that API by writing `perfume.start` and `perfume.end` or `perfume.endPaint`.

This should help you out mark and measure particular pieces of your page. Also one more thing, using this API is quite cheap, it takes 1ms for start and 1ms for end. @ElvisWang27 so feel free to add 3 or 4 combination of this metric and see which one works better for your case, and remember to name each mark with a different names.

**Comment by noamr** [comment]
I also find that IntersectionObserver is a useful metric for many experience-centric use cases, as it reaponds to particular elements coming into view.

**Comment by ElvisWang27** [comment]
@Zizzamia @noamr thanks  for help！！！
According to the above，the key point to measure in these browser is to create a custom metric  rather than create a polyfil for the `PerformancePaintTiming`and have them pretending to be equivalent to FCP.


> I also find that IntersectionObserver is a useful metric for many experience-centric use cases, as it reaponds to particular elements coming into view.
It's a good idea, I will try it . But this api also need [`intersection-observer`](https://www.npmjs.com/package/intersection-observer) polyfill to get lager support.

I have another question,  the time mark in `requestAnimationFrame`  can use as a metric meaning browser going to  paint the next frame?
