### ISSUE TITLE
tsconfig target

### ISSUE THREAD

**Issue by morganpizzini** [Zizzamia/perfume.js#89]
Scenario:
- Create a new application with `ng new my-app`
- Install library and follow the guidelines
- Add `@PerfumeAfterViewInit('AppComponent')` decorator
- Run application

I got the error below
```
Class constructor AppComponent cannot be invoked without 'new'
    at new childConstuctor (perfume.js-angular.js:95)
    at new newCtor (perfume.js-angular.js:98)
    at createClass (core.js:31984)
```

After some search I found out that the problem is tsconfig's target: by default it is **es2015**, but for make perfume.js works I have to change in **es5**.

This change works for me but I don't know if it's the right way to avoid the problem, if it's the correct way I could make a PR with updated README.md file

**Comment by Zizzamia** [comment]
Yeah, the `PerfumeAfterViewInit` decorator with Angular 9 is pretty much failing all the time.
I am thinking to get rid of the decorator at all and just keep only the Angular Perfume instance.

**Comment by Zizzamia** [comment]
@morganpizzini actually I decided to stop supporting custom Framework version starting from v5 https://github.com/Zizzamia/perfume.js/releases/tag/v5.0.0-rc.1  ☕️, mostly because Perfume is a very simple Vanilla library which is not too hard to include in any library. Sorry if this news comes out without a proper warning.

Perfume.js v5 contains some breaking changes so please feel free to open a new issue or ask me more questions if something unusual comes up.

Grazie Mille 💛
